name: cs3264-project-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - notebook=7.2
  - tqdm
  - pip:
      - transformers # For BERT / DistilBERT
      - datasets # To load the SMS Spam dataset
      - evaluate # For standardized metric calculation (F1, Accuracy)
